### ISSUE TITLE
Improve feed with load older notes

### ISSUE THREAD

**Issue by bitcoinuser** [leo-lox/camelus#12]
Hi,

I like the way Camelus feed works: when I open Camelus, the feed show exactly how it was the last time I closed Camelus, then start to show new notes. 
But I think between the last note when I closed Camelus and the new ones that start to show, could have a button like: Show older 10 new notes. So I could see older notes until arrive in the note of the last time I closed Camelus. 

Thanks.

**Comment by leo-lox** [comment]
I don't quite understand the last part with the button.
I had a twitter like system before but because of to many bugs I removed it again. But sooner or later such a system is nessecary.

**Comment by bitcoinuser** [comment]
> I don't quite understand the last part with the button. I had a twitter like system before but because of to many bugs I removed it again. But sooner or later such a system is nessecary.

Ex: I open Camelus and see the feed with same info when I last closed Camelus, right? So a new note appear, so I see note from 1 second ago and the next for for ex 2 days ago. So my idea is that between these two notes, could have a button like: show past 10 notes, and so on, until arrive the note of when I last closed Camelus, from 2 days ago. Understand?

**Comment by leo-lox** [comment]
got it, wasn't aware of that, but you are right thx!

**Comment by leo-lox** [comment]
still need to test it over a longer period. With what i could test it worked, reopen this if that is not the case

**Comment by bitcoinuser** [comment]
Will test when update appear on playstore.
