### ISSUE TITLE
When I click in a message that is a reply to other, the other never appear

### ISSUE THREAD

**Issue by bitcoinuser** [leo-lox/camelus#13]
Hi,

When I click in a message that is a reply to other, the other never appear.

![photo_2023-03-19_10-37-37](https://user-images.githubusercontent.com/1178856/226178773-3004e000-ae80-43f5-91ea-15672e098c3f.jpg)

**Comment by leo-lox** [comment]
yes, its not compatible with the updated nip spec. I will work on thread view it also needs some gossip improvments

**Comment by leo-lox** [comment]
happens on rare occasions when note is not spec
