### ISSUE TITLE
I had an experience of my feed miss a note of someone I'm following.

### ISSUE THREAD

**Issue by bitcoinuser** [leo-lox/camelus#15]
Hi,

I had an experience of my feed miss a note of someone I'm following.

Thanks.

**Comment by leo-lox** [comment]
Thats hard to debug. The issue here are the relays, maybe that note wasnt published to the relays gossip selected. What usually helps is to go onto their profile to fetch the contact data. I will automate this in gossip part II update.

**Comment by leo-lox** [comment]
=> #22
