### ISSUE TITLE
Push to refresh my feed, do not show new notes. Only show new notes on my feed if first I go to global feed.

### ISSUE THREAD

**Issue by bitcoinuser** [leo-lox/camelus#16]
Hi,

Push to refresh my feed, do not show new notes. Only show new notes on my feed if first I go to global feed. See the video:

https://user-images.githubusercontent.com/1178856/226183841-658274c5-af0f-4d90-b7e7-cf11a24d64c4.mp4

**Comment by leo-lox** [comment]
i will remove pull to refresh since it is addicting (dark pattern). I will stream notes directly or popup a button or something. 
you dont need to go to global, going to feed & replies and back replaces the subscription

**Comment by leo-lox** [comment]
thx for all the testing 🙏

**Comment by bitcoinuser** [comment]
> i will remove pull to refresh since it is addicting (dark pattern). I will stream notes directly or popup a button or something. you dont need to go to global, going to feed & replies and back replaces the subscription

Why not something like global feed, show total new notes on top and when clicked, show it?

**Comment by leo-lox** [comment]
because it was faster and I couldn't find the issue pull to refresh renew the subscription
