### ISSUE TITLE
Strange: tried to post something using Camelus and didn't work.

### ISSUE THREAD

**Issue by bitcoinuser** [leo-lox/camelus#17]
Hi,

Strange: tried to post something using Camelus and didn't work.

https://user-images.githubusercontent.com/1178856/226188428-cd680406-316a-465a-a07e-febdb321feeb.mp4

**Comment by bitcoinuser** [comment]
I tested again and worked. But for sure exist some problem here. When I tested, no error messages appeared.

**Comment by leo-lox** [comment]
yes, seen it as well will look into it. I think the write relays may disconnect and are currently not handled well

**Comment by leo-lox** [comment]
now gives err msg when no relay accepted the note
