### ISSUE TITLE
There are some profiles that avatar image never loads

### ISSUE THREAD

**Issue by bitcoinuser** [leo-lox/camelus#19]
Hi,

There are some profiles that avatar image never loads.

https://user-images.githubusercontent.com/1178856/226344892-2bea9cd9-f761-4b9d-9d5b-e67e089b6e5b.mp4

**Comment by leo-lox** [comment]
interesting can you post the npub ob that profile here?

**Comment by bitcoinuser** [comment]
> interesting can you post the npub ob that profile here?

npub1a2cww4kn9wqte4ry70vyfwqyqvpswksna27rtxd8vty6c74era8sdcw83a

**Comment by leo-lox** [comment]
fixed with https://github.com/leo-lox/camelus/pull/36
