### ISSUE TITLE
Camelus shouldn't automatically jump the feed to newest note

### ISSUE THREAD

**Issue by bitcoinuser** [leo-lox/camelus#21]
Hi,

When I open Camelus, I wouldn't like see the feed jump to newest note. I would like to stay where I was when I closed it. So then Camelus shoud show the counter on top and only if I click on counter, Camelus should jump automatically to top, to newest  note. The same way https://tweetoshi.com/ app works.

https://user-images.githubusercontent.com/1178856/226347716-11754b83-a2eb-4817-abcb-21b39e4ea5d7.mp4

**Comment by leo-lox** [comment]
thats what i ment with https://github.com/leo-lox/camelus/issues/16#issuecomment-1475282331 its on my todo list.
Hope I find time relatively soon to do this

**Comment by leo-lox** [comment]
I tried several things in [this branch](https://github.com/leo-lox/camelus/tree/user-feed-ui ), but nothing really worked. I guess it's a flutter thing. Will go back to it after some bugs.

**Comment by bitcoinuser** [comment]
> I tried several things in [this branch](https://github.com/leo-lox/camelus/tree/user-feed-ui), but nothing really worked. I guess it's a flutter thing. Will go back to it after some bugs.

Yes, tested here the new version and its not working as expected. Thanks

**Comment by leo-lox** [comment]
top notification is shown on new notes
