### ISSUE TITLE
Many times the newest note appear with profile image of the second newest note

### ISSUE THREAD

**Issue by bitcoinuser** [leo-lox/camelus#25]
Hi,

Many times the newest note appear with profile image of the second newest note. Only update to the correct image when I push to update. See the video:

https://user-images.githubusercontent.com/1178856/226776525-04a40d34-dc79-41c9-a007-e24f1993d1ef.mp4

**Comment by bitcoinuser** [comment]
As I can see, not only the second one. The notes text of others are correct but names and images wrong. Only show correct names and images on push to update.

**Comment by leo-lox** [comment]
fixed with https://github.com/leo-lox/camelus/pull/36
