### ISSUE TITLE
add the #nostr tag to this repo

### ISSUE THREAD

**Issue by gourcetools** [leo-lox/camelus#4]
add the #nostr tag to this repo

**Comment by leo-lox** [comment]
Do you mean topics? Or git tag?

**Comment by gourcetools** [comment]
huh yeah sorry, i mean topics from the about page on web. thank you a lot
![image](https://user-images.githubusercontent.com/120996278/214191777-0caf31c7-dbc0-42fa-ae28-b87696929582.png)

**Comment by leo-lox** [comment]
added them, thx 🙏
