### ISSUE TITLE
I still see posts of people I muted on Amethyst

### ISSUE THREAD

**Issue by bitcoinuser** [leo-lox/camelus#51]
Hi,

Looks like there's no interoperability between the mute from Amethyst on Camelus. I muted some profiles on Amethyst client but when using Camelus, I see posts from these people I muted.

Thanks.

**Comment by 1-leo** [comment]
Thx for reporting, camelus is still in beta and mute block and report does not work yet. 
I added this to the public bug tracker:
https://github.com/users/leo-lox/projects/3/views/1
